
var as = {};

as["IPS"]="This is the layout of the Indoor Positioning System (IPS). Click to bring up a description of each component. (Note: There are multiple levels of objects. After clicking on the RPi, you can click on the camera, cable and board)."
as["Raspberry Pi"] = "The Raspberry Pi is a credit-card sized computer that plugs into your TV and a keyboard. It is a capable little computer which can be used in electronics projects, and for many of the things that your desktop PC does, like spreadsheets, word-processing and games. It also plays high-definition video. We want to see it being used by kids all over the world to learn how computers work, how to manipulate the electronic world around them, and how to program.";
as["Cat5 Cable"]="Category 5 cable (cat 5) is a twisted pair cable for carrying signals. This type of cable is used in structured cabling for computer networks such as Ethernet. The cable standard provides performance of up to 100 MHz and is suitable for 10BASE-T, 100BASE-TX (Fast Ethernet), and 1000BASE-T (Gigabit Ethernet). Cat 5 is also used to carry other signals such as telephony and video.";
as["RaspiCam"]="The Raspberry Pi camera module can be used to take high-definition video, as well as stills photographs. It's easy to use for beginners, but has plenty to offer advanced users if you're looking to expand your knowledge. There are lots of examples online of people using it for time-lapse, slow-motion and other video cleverness. You can also use the libraries we bundle with the camera to create effects.";
as["IPS Node"]="In communication networks, a node (Latin nodus, 'knot') is either a connection point, a redistribution point or a communication endpoint (some terminal equipment). The definition of a node depends on the network and protocol layer referred to. A physical network node is an active electronic device that is attached to a network, and is capable of sending, receiving, or forwarding information over a communications channel. A passive distribution point such as a distribution frame or patch panel is consequently not a node.";
as["Switch"]="A network switch is a computer networking device that connects devices together on a computer network, by using a form of packet switching to forward data to the destination device. A network switch is considered more advanced than a (repeater) hub because a switch will only forward a message to one or multiple devices that need to receive it, rather than broadcasting the same message out of each of its ports.[1]";
as["Ground Station"]="A ground control station (GCS) is a land- or sea-based control center that provides the facilities for human control of unmanned vehicles in the air or in space. A GCS could be used to control unmanned aerial vehicles or grounded vehicles.";
as["Computer"]="The IPS uses two computers. One, running Dickson College's IPS-Server software, is an interface between the Raspberry Pis and the UAVs. The other, like in a normal UAV mission, runs APM Mission Planner to control the autopilot.";
as["XBee"]="XBee is the brand name from Digi International for a family of form factor compatible radio modules. The first XBee radios were introduced under the MaxStream brand in 2005 and were based on the 802.15.4-2003 standard designed for point-to-point and star communications at over-the-air baud rates of 250 kbit/s.";
as["Car"]='Radio controlled (or R/C) cars are self-powered model cars or trucks that can be controlled from a distance using a specialized transmitter or remote. The term "R/C" has been used to mean both "remote controlled" and "radio controlled", where "remote controlled" includes vehicles that are connected to their controller by a wire, but common use of "R/C" today usually refers to vehicles controlled by a radio-frequency link. This article focuses on radio-controlled vehicles only.';
as["UAV"]="An unmanned aerial vehicle (UAV), commonly known as a drone and referred to as a Remotely Piloted Aircraft (RPA) by the International Civil Aviation Organization (ICAO), is an aircraft without a human pilot aboard. There are different kinds of drones.";
as["GPS"]="The Global Positioning System (GPS) is a space-based satellite navigation system that provides location and time information in all weather conditions, anywhere on or near the Earth where there is an unobstructed line of sight to four or more GPS satellites. The system provides critical capabilities to military, civil and commercial users around the world. It is maintained by the United States government and is freely accessible to anyone with a GPS receiver.";
as["Pixhawk"]="Pixhawk is an advanced autopilot system designed by the PX4 open-hardware project and manufactured by 3D Robotics. It features advanced processor and sensor technology from ST Microelectronics® and a NuttX real-time operating system, delivering incredible performance, flexibility, and reliability for controlling any autonomous vehicle.";
as["Tele"]="3DR Radios allow your ground station computer to communicate with your vehicle wirelessly, providing unparalleled ease of use for viewing in-flight data, changing missions on the fly, and tuning.";
